(() => {
 'use strict';
 const $=id=>document.getElementById(id), q=new URLSearchParams(location.search),handle=q.get('h')||'alex',demo=q.has('demo')||location.protocol==='file:';
 const API='https://api.humanvoiced.com';
 const database=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('humanvoiced-studio-v1',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('recordings'))r.result.createObjectStore('recordings')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 const localClip=async()=>{try{const db=await database();return await new Promise((resolve,reject)=>{const r=db.transaction('recordings').objectStore('recordings').get('pending-onboarding');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});}catch{return null}};
 function el(tag,attr={},text=''){const n=document.createElement(tag);for(const [key,value] of Object.entries(attr))if(key==='class')n.className=value;else n.setAttribute(key,value);if(text)n.textContent=text;return n;}
 function show(p){const profile=p.profile||p;const name=profile.display_name||p.handle||'Unnamed narrator';$('display-name').textContent=name;$('avatar').textContent=name.charAt(0).toUpperCase();$('handle-label').textContent='@'+(p.handle||handle);$('bio').textContent=profile.bio||'Natural voice samples available for you to hear.';$('about-copy').textContent=profile.bio||'This narrator has not added a bio yet.';let languages=p.languages||profile.languages||[];$('languages').textContent='Languages: '+(languages.length?languages.join(', '):'not specified');const tags=$('tags');tags.replaceChildren();for(const item of [profile.accent_description?.text,...(profile.categories||[]),...languages].filter(Boolean)){tags.append(el('span',{class:'tag'},item));}const samples=(p.samples||[]);$('sample-count').textContent=samples.length;const rep=p.reputation||{};$('jobs-count').textContent=rep.completed||'—';const box=$('samples');box.replaceChildren();if(!samples.length){box.append(el('div',{class:'placeholder'},'No public voice samples yet. The narrator must explicitly approve the recording before it becomes visible.'));return;}for(const s of samples){const row=el('div',{class:'audio-tile'});row.append(el('div',{class:'row between'},''));row.firstChild.append(el('strong',{},s.kind||'Natural narration'));row.firstChild.append(el('span',{class:'tag'},s.language||'Voice sample'));const a=el('audio',{controls:'',preload:'none'});if(demo&&s.kind==='natural'){localClip().then(b=>{if(b)a.src=URL.createObjectURL(b)});}else if(/^[0-9a-f]{64}$/i.test(s.sha256||'')){a.src=API+'/v1/voices/'+encodeURIComponent(p.narrator_id||p.id)+'/sample?sha='+encodeURIComponent(s.sha256);}row.append(a);row.append(el('span',{class:'small muted'},'Recorded by this narrator · Published with permission'));box.append(row);}}
 for(const tab of document.querySelectorAll('.tab'))tab.onclick=()=>{for(const t of document.querySelectorAll('.tab'))t.classList.toggle('active',t===tab);for(const x of ['samples','work','about'])$('tab-'+x).classList.toggle('hidden',tab.dataset.tab!==x)};
 async function load(){if(demo){const stored=JSON.parse(localStorage.getItem('hv-demo-profile')||'null');show(stored||{handle:'samplevoice',profile:{display_name:'Your voice, your way',bio:'This is an interactive portfolio preview. Record your own sample in Voice Studio to see it appear here.',languages:['English'],categories:['Storytelling','YouTube narration']},samples:[],reputation:{completed:0}});return;}try{const response=await fetch(API+'/v1/voices/by-handle/'+encodeURIComponent(handle));if(!response.ok)throw new Error('Voice not found');show(await response.json());}catch(e){$('display-name').textContent='Portfolio unavailable';$('bio').textContent='This narrator has not published a public portfolio, or the API is unavailable.';$('samples').replaceChildren(el('div',{class:'placeholder'},e.message));}}
 load();
})();
